# Generated by Django 4.0.4 on 2022-07-24 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_stocks_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocks',
            name='status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Default', 'Default')], default='Default', max_length=200),
        ),
    ]
