# Generated by Django 4.0.4 on 2022-07-24 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_stocks'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocks',
            name='status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default=0, max_length=20),
            preserve_default=False,
        ),
    ]
